/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.Test;
import static org.junit.Assert.*;

public class MonsterTest {
  @Test
  public void testMonster() {
    Monster monster = new Monster();
    assertEquals(5, calculate.sum_loop(2, 3, 0)); // 2 + 3
    assertEquals(55, calculate.sum_loop(1, 10, 0)); // 1 + 2 + ... + 10
    assertEquals(25, calculate.sum_loop(1, 10, 1)); // 1 + 3 + 5 + 7 + 9 (odd)
    assertEquals(30, calculate.sum_loop(1, 10, 2)); // 2 + 4 + 6 + 8 + 10 (even)
  }
}
