
/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.junit.Assert.assertEquals;

public class PlayerTest {

    @Test
    public void testDrawMonsters() {
        Player player = new Player();
        player.drawMonsters();
        assertEquals(5, player.deck.size());

        for (Monster m : player.deck) {
            assertNotNull(m);
            assertTrue(m.toString().matches(".+レア度\\[\\d+\\]\\n"));
        }
    }

    @Test
    public void testShowDeck() {
        Player player = new Player();
        player.drawMonsters();

        // 出力の検証を行うために標準出力をリダイレクトする
        java.io.ByteArrayOutputStream outContent = new java.io.ByteArrayOutputStream();
        System.setOut(new java.io.PrintStream(outContent));

        player.showDeck();

        String output = outContent.toString();
        String[] lines = output.split("\n");

        // デッキのサイズと出力の行数を確認
        assertEquals(5, player.deck.size());
        assertEquals(5, lines.length);
    }
}
